### ISSUE TITLE
ERROR: Wrong command 'attach'

### ISSUE THREAD

**Issue by Liv1020** [vukor/docker-lnmp#17]
how to use it

**Comment by vukor** [comment]
Hello.
Please, write complete command.

p.s. now we don't use this project. Please, see https://github.com/vukor/docker-web-stack
p.p.s. thanks for using my project :)

**Comment by Liv1020** [comment]
I use ```$ dw attach,
thank you tell me another repository

**Comment by vukor** [comment]
now i don't support this project, all functions are available in project https://github.com/vukor/docker-web-stack
